--[[
    Wrote with : VSCode Lua Module
    From sumneko
    ]]
    
WP_FIST = "FIST"
WP_DEAGLE = "DEAGLE"
WP_COLT = "COLT"
WP_GLOCK = "GLOCK"
WP_BERETTA = "BERETTA"
WP_AUTOSHOTGUN = "AUTOSHOTGUN"
WP_SHOTGUN = "SHOTGUN"
WP_MP5S = "MP5S"
WP_UZI = "UZI"
WP_UMP = "UMP"
WP_M16A4 = "M16A4"
WP_AK47 = "AK47"
WP_AK47G = "AK47G"
WP_G36C = "G36C"
WP_VSS = "VSS"
WP_AK74U = "AK74U"
WP_M4A1 = "M4A1"
WP_ACR = "ACR"
WP_M4A4 = "M4A4"
WP_AWP = "AWP"